### ISSUE TITLE
error inside editor.ts

### ISSUE THREAD

**Issue by ShaquibKhanhub** [adityaphasu/notion-clone#1]
"use client";

import { BlockNoteEditor, PartialBlock } from "@blocknote/core";
import { BlockNoteViewRaw, useCreateBlockNote } from "@blocknote/react";
import "@blocknote/core/style.css";
import { useTheme } from "next-themes";
import { useEdgeStore } from "@/lib/edgestore";

interface EditorProps {
  onChange: (value: string) => void;
  initialContent?: string;
  editable?: boolean;
}

const Editor = ({ onChange, initialContent, editable }: EditorProps) => {
  const { resolvedTheme } = useTheme();
  const { edgestore } = useEdgeStore();

  const handleUpload = async (file: File) => {
    const res = await edgestore.publicFiles.upload({
      file,
    });

    return res.url;
  };

  const editor: BlockNoteEditor = useCreateBlockNote({
    editable,
    initialContent: initialContent
      ? (JSON.parse(initialContent) as PartialBlock[])
      : undefined,
    uploadFile: handleUpload,
  });

  // Update your `onChange` handler according to the expected signature
  const handleEditorChange = () => {
    onChange(JSON.stringify(editor.document, null, 2));
  };

  return (
    <div>
      <BlockNoteViewRaw
        editor={editor}
        theme={resolvedTheme === "dark" ? "dark" : "light"}
        onChange={handleEditorChange}
      />
    </div>
  );
};

export default Editor;
inside your editor code some things are deprecated like these BlockNoteViewRaw, useCreateBlockNote and also can't use onChange inside editot function so somehow I fix this ' onChange={handleEditorChange} ' but now when I'm hovering on the sidebar I'm getting this error Unhandled Runtime Error
TypeError: Cannot read properties of undefined (reading 'SideMenu') could you please help me on this

**Comment by adityaphasu** [comment]
Hey @ShaquibKhanhub! Thanks for letting me know! 

Yeah, it's been a while since I last checked and I didn't notice that Blocknote updated their documentation! Now you have to install one more package called `"@blocknote/mantine"` which has the `BlockNoteView` component for the editor and the documentation specifies it for use. Don't use the `BlockNoteViewRaw` from @blocknote/react... I couldn't find its usage.

I have updated the code and used it instead and it's working fine now.

Key changes are: 
- use `BlockNoteView` from `"@blocknote/mantine"`
- import in the styles of the editor using `"@blocknote/mantine/style.css"`
- instead of `useBlockNote` use `useCreateBlockNote` instead
- instead of using the `editable` prop inside the `useCreateNoteBlock`, pass it to the editable prop for the `BlockNoteView` which now allows it as a prop ( saw it from the documentation, and now it's quite easy!)

Thanks for letting me know! You can take a look at the `editor.tsx` file or the recent commit to see the changes! ❤️

**Comment by ShaquibKhanhub** [comment]
Hey @adityaphasu! Thank you so much for your quick response.

I'm so grateful that you have looked into my issue and **resolved** it, I also read the **documentation** but I was not importing from it **"@blocknote/mantine"** Here I put a lot of time into this but I was not able to correct it. But because of you, it's also working in my app.

But again Thanks for your quick response, I'm so grateful.
